### ISSUE TITLE
Pricing page in unprocurable.

### ISSUE THREAD

**Issue by mustafa2mujahid** [ganupadval/Dog-Tinder#5]
Somethings' wrong with the pricing page. Whenever i try to access it the servers time getting out and displaying this site can't be reached. Please fix it soon.

**Comment by ganupadval** [comment]
Thanks for addressing it, if you want to contribute for the same please let me know.

**Comment by mustafa2mujahid** [comment]
Yeah i am up for it. I'll do my best.
